Improved Embeds.md
Javacord/Website pull request #16
Opened 2020-12-23 10:28 UTC by YT-GameWorks

The original one was too vague, and unclear so I put in 2 sections describing some of the methods

2020-12-23 18:37 UTC, Joshix-1 requested changes
I don't think we need this at all, because the current explains it enough in combination with the docs.
But here are some suggestions on things you can improve.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +To start using the embed builder, you need to instantiate it like any other class and then you can start acessing it's methods. We'll go through the basic ones here:
*accessing

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setTitle("")`- Most of the time you will want a title for your embed, won't you :question: This sets the title of the embed, the top-most words in the embed.
EmbedBuilder#setTitle() is like the other methods not static. You shouldn't use a dot there.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.addFeild("", "", false)`- So if you want more subtitles than your description, This is the way to do that! thats cool and all, but what are the 3 parameters? The first one is the subt
it's field not feild

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setTitle("")`- Most of the time you will want a title for your embed, won't you :question: This sets the title of the embed, the top-most words in the embed.
And I don't think you should use "" as a placeholder for Strings. You can't even set it to an empty String.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.addFeild("", "", false)`- So if you want more subtitles than your description, This is the way to do that! thats cool and all, but what are the 3 parameters? The first one is the subt
Maybe mention here that one can achieve empty fields with invisible characters like "\u200B"

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setColor(Color)`- This setts the color on the side of the embed... The way you use it is create a new color class, like so: `Color embedColor = new Color(r, g, b)` and put the RGB (in
*sets with one t

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setColor(Color)`- This setts the color on the side of the embed... The way you use it is create a new color class, like so: `Color embedColor = new Color(r, g, b)` and put the RGB (in
I don't think we should explain basic java classes in this.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setColor(Color)`- This setts the color on the side of the embed... The way you use it is create a new color class, like so: `Color embedColor = new Color(r, g, b)` and put the RGB (in
It is IntelliJ IDEA, but I don't think we should mention this here.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setImage("")`- Adds an Image to the bottom of the embed, This can edither be a link to a image on the web or one stored on your computer.
edither → either

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setThumbnail("")`- Adds an image to the embed but this time at the right side of it! aThis can either be a link or a local file.
aThis → This

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setAuthor("", "")`- This adds text to the top of the embed (above the title), you can make it dynamic by using `event.getMessageAuthor().getDisplayName();`, It has an optional second
Shouldn't it be clear that you can put any Strings here?

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.getTimestamp()`- gets the timesStamp of the embed, useful for when you have to add a footer and set it to the time the message was sent.
This is no method.

2020-12-23 18:37 UTC, Joshix-1 commented on docs/wiki/basic-tutorials/embeds.md
> +* `EmbedBuilder.setImage("")`- Adds an Image to the bottom of the embed, This can edither be a link to a image on the web or one stored on your computer.
The String in EmbedBuilder#setImage(String url) can only be an url to an external image. To send local images you need one of the other setImage methods

2020-12-24 08:50 UTC, YT-GameWorks commented
Hello, thanks for pointing out the mistakes, it is my first time writing a wiki, also I think we really need this as a beginner I was confused by the wiki with just a embed example with no detailed explanation, at least explain the more complex ones! I know a lot of them are self explanatory but I was confused by it a lot... Anyway I will continue to improve this...

2020-12-27 12:46 UTC, Bastian commented
Hi, thank you for the Pull Request!

I have to agree with Joshix, that it is probably not a good idea to just explain every single method, as we also don't do it in any of the other wiki articles.

What do you think about adding information to the example image itself like this:
![image](https://user-images.githubusercontent.com/5033001/103171111-dc411f80-4849-11eb-9fe6-46ca826a48a7.png)

2021-03-17 06:47 UTC, closed without merging